/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.thomas.rsql.mybatis.plus;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
